# GNUmakefile
#
#
# Written by: Stefan Urbanek
# Date: 2002 May 18
#

include $(GNUSTEP_MAKEFILES)/common.make

MODEL_NAME = TrustModel

TrustModel_OBJC_FILES= \
        TrustModelWorld.m \
        TrustAgent.m \
        TrustCouple.m \
        Memory.m \
        TrustRelationship.m

include afmodel.make
