# GNUmakefile
#
#
# Written by: Stefan Urbanek
# Date: 2002 May 18
#

include $(GNUSTEP_MAKEFILES)/common.make

MODEL_NAME = SourceFinder

SourceFinder_OBJC_FILES= \
        SourceFinderSimulation.m \
        WalkingAgent.m \
        EnergySource.m \
        NSArray+additions.m \
        NSDictionary+additions.m 

include afmodel.make
