#
#  GNUmakefile
#

include $(GNUSTEP_MAKEFILES)/common.make

MODEL_NAME   = TestRandom
PACKAGE_NAME = TestRandomModel
VERSION      = 0.1

TestRandom_OBJC_FILES = \
        World.m


include afmodel.make
