#
#  GNUmakefile
#

include $(GNUSTEP_MAKEFILES)/common.make

MODEL_NAME   = Template
PACKAGE_NAME = TemplateModel
VERSION      = 0.1
Template_OBJC_FILES = \
        TemplateWorld.m


include afmodel.make
